template: 5aa7157c7f6b080001a7d8f6
name: basic-vns-2nsgs
expires: "2018-12-31T17:13:11.278Z"
sshKeys:
  - name: demo
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0jLLF2c7sSUHCwFJ1cpj0mTNRfemi6XMKxAf7H4gIzs/joL18W+wlSrnHnu801bDLc2RNg8dvOvXmzjzZrKKMInWMXrzb0zjljCPumYWlI/koWAIMzpENjeRjWrB22WFVOVDW4GkphzhchFWFPSF9xxU4i3MPHn3HYZiy6ieLOvknplQDivTXcLwRjvenK35gjLPxo4nFhQWyUdzPLLCb/NUx/CGjkh10qwVfw+AWw3x3boqxwBXitPjLJ+ocfZVohAWupKuvsTNzlh8m39imI5pi9qTFT1x9YtkYsTYCy2iz2HCirqy+8BC/CPCyHuEjs8ZT9OFHHQtjB/qgzfTp"

services:
  # - name: vsd
  #   type: public
  #   port: 8443
  #   urlScheme: https
  #   protocols:
  #   - tcp
  #   destination:
  #     port: 18443
  #     address: 10.0.0.2
  - name: rdp-branchpc1
    type: public
    port: 33891
    protocols:
    - tcp
    destination:
      port: 3389
      address: 10.0.0.101
  - name: rdp-branchpc2
    type: public
    port: 33892
    protocols:
    - tcp
    destination:
      port: 3389
      address: 10.0.0.102
  - name: amqp
    type: public
    port: 5672
    protocols:
    - tcp
    destination:
      port: 5672
      address: 10.0.0.2

networks:
  # - name: private
  #   cidr: 10.0.0.0/24
  #   dns:
  #   - 10.0.0.1
  #   dhcp: true
  - name: dummy1
    cidr: "255.255.255.0/24"
    dns:
    dhcp: false

  - name: nsg1-lan
    cidr: "172.17.1.0/24"
    dns: "10.0.0.1"
    dhcp: false
  
  - name: nsg2-lan
    cidr: "172.17.2.0/24"
    dns: "10.0.0.1"
    dhcp: false

servers:
  # - name: vsd01
  #   image: vsd01_NUX-VNS-5.2.2
  #   flavor: nux.vsd
  #   interfaces:
  #   - index: 0
  #     network: private
  #     address: 10.0.0.2
  # - name: vsc01
  #   image: vsc01_NUX-VNS-5.2.2
  #   flavor: m1.small
  #   interfaces:
  #   - index: 0
  #     network: private
  #     address: 10.0.0.3
  # - name: utility
  #   image: utility_NUX-VNS-5.2.2
  #   flavor: m1.small
  #   interfaces:
  #   - index: 0
  #     network: private
  #     address: 10.0.0.33
  # - name: elastic
  #   image: elastic_NUX-VNS-5.2.2
  #   flavor: nux.vsd
  #   interfaces:
  #   - index: 0
  #     network: private
  #     address: 10.0.0.5
  - name: nsg1
    flavor: "m1.small"
    image: "nux_nsg_5.2.2"
    interfaces:
      - network: private
        address: "10.0.0.11"
        index: 0
      - network: dummy1
        address: "255.255.255.1"
        index: 1
      - network: nsg1-lan
        address: "172.17.1.1"
        index: 2
  - name: pc1
    image: "nux_branch_pc"
    flavor: "m1.small"
    interfaces:
      - index: 0
        network: private
        address: "10.0.0.101"
      - index: 1
        network: nsg1-lan
        address: "172.17.1.101"

  - name: nsg2
    flavor: "m1.small"
    image: "nux_nsg_5.2.2"
    interfaces:
      - network: private
        address: "10.0.0.12"
        index: 0
      - network: dummy1
        address: "255.255.255.2"
        index: 1
      - network: nsg2-lan
        address: "172.17.2.1"
        index: 2
  - name: pc2
    image: "nux_branch_pc"
    flavor: "m1.small"
    interfaces:
      - index: 0
        network: private
        address: "10.0.0.102"
      - index: 1
        network: nsg2-lan
        address: "172.17.2.102"